In [2]:
import tensorflow as tf
import pennylane as qml
import numpy as np
import sys
from qGAN import qGAN, create_qGAN

Here we will train the qGAN created in the file qGAN.py and train it on some simple examples.
First, a function to create arbitrary adjacency matrices.

In [3]:
def random_adjacency_matrix(n):
    """
    creates an nxn symmetric adjacency matrix with 0s along the diagonal
    used to represent an undirected graph with n nodes
    :param n: dimension
    :return: nxn numpy array
    """
    matrix = [[np.random.randint(0, 1) for i in range(n)] for j in range(n)]
    # No vertex connects to itself
    for i in range(n):
        matrix[i][i] = 0
    # If i is connected to j, j is connected to i
    for i in range(n):
        for j in range(n):
            matrix[j][i] = matrix[i][j]
    return np.array(matrix)

In [9]:
dataset = [random_adjacency_matrix(3) for _ in range(20)]
create_qGAN(dataset[0], dataset, 50)




Gen cost: [-0.50156571]
Disc cost: [0.01575611]
Generated sample:
[[1. 1. 1.]
 [1. 1. 0.]
 [1. 0. 1.]]
Gen cost: [-0.50231515]
Disc cost: [0.012338]
Generated sample:
[[1. 1. 1.]
 [1. 1. 0.]
 [1. 0. 1.]]
Gen cost: [-0.502732]
Disc cost: [0.01013957]
Generated sample:
[[1. 1. 1.]
 [1. 1. 0.]
 [1. 0. 1.]]
Gen cost: [-0.50288859]
Disc cost: [0.00848263]
Generated sample:
[[1. 1. 1.]
 [1. 1. 0.]
 [1. 0. 1.]]
Gen cost: [-0.50285215]
Disc cost: [0.00709109]
Generated sample:
[[1. 1. 1.]
 [1. 1. 0.]
 [1. 0. 1.]]
Gen cost: [-0.50268021]
Disc cost: [0.00584938]
Generated sample:
[[1. 1. 1.]
 [1. 1. 0.]
 [1. 0. 1.]]
Gen cost: [-0.50241899]
Disc cost: [0.0047069]
Generated sample:
[[1. 1. 1.]
 [1. 1. 0.]
 [1. 0. 1.]]
Gen cost: [-0.50210318]
Disc cost: [0.00363627]
Generated sample:
[[1. 1. 1.]
 [1. 1. 0.]
 [1. 0. 1.]]
Gen cost: [-0.50175679]
Disc cost: [0.00261414]
Generated sample:
[[1. 1. 1.]
 [1. 1. 0.]
 [1. 0. 1.]]
Gen cost: [-0.5013949]
Disc cost: [0.00161203]
Generated sample:
[[1. 1. 1.]
 

Penalties: We are getting lots of matrices with 1 on the diagonal, which we ideally don't want. We also want to penalise going to a  location twice. This means we want to penalise measurements of qubits 0, n+1, 2n+2, ..., n**2 - 1.
This is just the 