In [1]:
import tensorflow as tf
import pennylane as qml
import numpy as np
import sys
from qGAN import qGAN, create_qGAN

Here we will train the qGAN created in the file qGAN.py and train it on some simple examples.
First, a function to create arbitrary adjacency matrices.

In [2]:
def random_adjacency_matrix(n):
    """
    creates an nxn symmetric adjacency matrix with 0s along the diagonal
    used to represent an undirected graph with n nodes
    :param n: dimension
    :return: nxn numpy array
    """
    matrix = [[np.random.randint(0, 1) for i in range(n)] for j in range(n)]
    # No vertex connects to itself
    for i in range(n):
        matrix[i][i] = 0
    # If i is connected to j, j is connected to i
    for i in range(n):
        for j in range(n):
            matrix[j][i] = matrix[i][j]
    return np.array(matrix)

In [ ]:
dataset = [random_adjacency_matrix(3) for _ in range(50)]
create_qGAN(dataset[0], dataset, 30)




Instructions for updating:
Use tf.identity instead.


Instructions for updating:
Use tf.identity instead.


Gen cost: [3.64791615]
Disc cost: [-0.27474435]
Generated sample:
[[0. 1. 0.]
 [1. 0. 1.]
 [0. 0. 0.]]


Penalties: We are getting lots of matrices with 1 on the diagonal, which we ideally don't want. We also want to penalise going to a  location twice. This means we want to penalise measurements of qubits 0, n+1, 2n+2, ..., n**2 - 1.
This is just the Z expectation value of these qubits.

We also require that the qubits in each row and column have hamming weight 1. These qubits are $|0, 1, ..., n \rangle$, $|n + 0, n + 1, ..., n \rangle$, ... $|n**2 - n, ..., n**2 \rangle$.

And for the columns we have $|n*0, n*1, ..., n*(n-1) \rangle$, $|n*0 + 1, n*1 + 1, ..., n*(n-1) + 1 \rangle$, $|n*0 + n, n*1 + n, ..., n*(n-1) + n\rangle$.

